server:
  port: 8080

home:
  isAvailable: true
spring:
  profiles:
    active: dev
#
#logging:
#  path: /var/log/
#  file: Kaushal.log
#  level:
#    root: ERROR
#---
#
#
#spring:
#  profiles:
#    active: dev
#
#
#logging:
#  path: /var/log/
#  file: Kaushal.log
#  level:
#    root: INFO